// 100 passages of roughly 25 words, each teaching something worth knowing.
// Four themes: general knowledge, mental models, life skills, and why things are the way they are.
// ASCII letters, spaces, commas, periods and apostrophes only.
export const PASSAGES = [
  // General knowledge
  "Honey never spoils. Archaeologists have found pots of it in ancient Egyptian tombs that are over three thousand years old and still perfectly edible.",
  "An octopus has three hearts and blue blood. Two hearts pump blood through the gills, and the third stops beating whenever the animal swims.",
  "Bananas are berries, but strawberries are not. Botanically, a berry grows from a single flower with one ovary, and strawberries break that rule.",
  "Cleopatra lived closer in time to the first moon landing than to the building of the Great Pyramid of Giza, which was already ancient.",
  "Sharks are older than trees. The first sharks appeared over four hundred million years ago, while the earliest true trees came tens of millions later.",
  "A day on Venus is longer than its year. The planet turns so slowly that it circles the sun before completing a single full spin.",
  "Wombats produce cube shaped droppings. Their intestines have stretchy and stiff sections that shape the waste into neat blocks they use to mark territory.",
  "The Eiffel Tower grows about fifteen centimeters taller in summer, because the iron expands in the heat and shrinks back again in winter.",
  "Oxford University was already teaching students centuries before the Aztec capital of Tenochtitlan was founded, even though both feel ancient to us today.",
  "Your body has more bacterial cells than you might think, roughly as many as human cells, and most of them live quietly in your gut.",
  "Octopuses, squids, and cuttlefish can change color in a fraction of a second, even though most of them are thought to be colorblind.",
  "There are more possible ways to shuffle a deck of cards than there are atoms on Earth, so every good shuffle is almost certainly unique.",
  "Hot water can sometimes freeze faster than cold water. Scientists call this the Mpemba effect and still argue about exactly why it happens.",
  "A group of flamingos is called a flamboyance. They get their pink color from pigments in the shrimp and algae they eat, not from birth.",
  "Sound travels about four times faster through water than through air, which is why whales can hear each other across huge stretches of ocean.",
  "The human nose can tell apart an enormous number of different smells, and scent is closely tied to memory in the brain.",
  "Lightning strikes the Earth around forty to fifty times every second, adding up to well over a billion flashes across the planet each year.",
  "Sloths can hold their breath for up to forty minutes by slowing their heart rate, which is longer than many dolphins can manage.",
  "The shortest war in recorded history was between Britain and Zanzibar in eighteen ninety six. It lasted somewhere around forty minutes.",
  "Koalas sleep up to twenty hours a day, because their diet of eucalyptus leaves gives them very little energy and takes a long time to digest.",
  "Mount Everest is the tallest mountain above sea level, but Mauna Kea in Hawaii is taller when measured from its base on the ocean floor.",
  "Water expands when it freezes, which is why ice floats. If ice sank, lakes would freeze from the bottom up and most fish would not survive.",
  "The heart of a blue whale is roughly the size of a small car, and its beat can be detected from miles away with underwater microphones.",
  "Humans share about sixty percent of their genes with bananas, which says less about bananas and more about how much basic cell machinery all life shares.",
  "Butterflies taste with their feet. Sensors on their legs tell them whether a leaf is the right plant to lay their eggs on.",

  // Mental models
  "Second order thinking means asking what happens next. Many bad decisions look fine at the first step and only go wrong at the second or third.",
  "Inversion means solving a problem backward. Instead of asking how to succeed, ask what would guarantee failure, and then carefully avoid doing those things.",
  "The map is not the territory. Every model, plan, and summary leaves things out, so check reality often instead of trusting the description alone.",
  "Occam's razor suggests that when several explanations fit the facts, the simplest one is usually the best place to start looking.",
  "The Pareto principle says a small share of causes often drives most results. Find the few things that matter most and spend your energy there.",
  "Opportunity cost is the value of the best thing you gave up. Every yes is quietly a no to something else, including this website.",
  "Sunk cost fallacy is continuing something only because you already invested in it. Past effort is gone, so decide based on what happens from here.",
  "Hanlon's razor says never attribute to malice what can be explained by carelessness. Most people are busy and distracted, not plotting against you.",
  "Confirmation bias makes us notice evidence that supports what we already believe. Actively look for the strongest argument against your own view.",
  "Compounding means small gains build on themselves. Getting one percent better every day adds up to something remarkable over a year.",
  "First principles thinking means breaking a problem down to basic truths and building up from there, instead of copying what everyone else already does.",
  "Circle of competence means knowing where your real knowledge ends. Stay inside it for big decisions, and be honest when you are outside it.",
  "Chesterton's fence warns against removing something before you understand why it was put there. Find out the reason first, then decide.",
  "The Dunning Kruger effect describes how beginners often feel most confident, while experts see how much they still do not know.",
  "Parkinson's law says work expands to fill the time available. Give a task a shorter deadline and it often gets done just as well.",
  "Survivorship bias is judging by the winners you can see while ignoring the failures you cannot. For every famous dropout, thousands quietly struggled.",
  "Regression to the mean means extreme results tend to be followed by more ordinary ones. A great day is often luck, not a new normal.",
  "Margin of safety means leaving room for error. Engineers build bridges to hold far more than expected, and you can plan your time the same way.",
  "Goodhart's law says when a measure becomes a target, it stops being a good measure, because people start gaming the number instead of the goal.",
  "The availability heuristic makes vivid events feel more common than they are. Plane crashes make the news, while ordinary car accidents rarely do.",
  "Reversible decisions can be made quickly, because mistakes are cheap to undo. Save your slow, careful thinking for choices that are hard to reverse.",
  "Anchoring happens when the first number you hear shapes every judgment after it. Before negotiating, decide what something is worth to you.",
  "Loss aversion means losing something hurts about twice as much as gaining the same thing feels good, which makes us cling to bad situations.",
  "The Lindy effect suggests that ideas and books that have lasted a long time are likely to keep lasting. Old wisdom has survived many tests.",
  "Thinking in probabilities means replacing yes or no with how likely. Few things are certain, and good decisions weigh the odds honestly.",

  // Life skills
  "To remember a name, say it back right away, link it to someone you already know with that name, and use it once more before you leave.",
  "If you cannot fall asleep after twenty minutes, get up and do something calm in dim light. Return to bed only when you feel sleepy.",
  "To calm down quickly, breathe in for four counts, hold for four, breathe out for four, and hold for four. Repeat it a few times.",
  "When giving feedback, describe the specific behavior, explain its effect, and suggest what would help. Keep it about the work, not the person.",
  "Before a hard conversation, write down the one thing you want the other person to understand. It keeps you focused when emotions run high.",
  "To write a clear email, put the request in the first line, keep it short, and make the next step obvious. Busy people skim everything.",
  "The two minute rule says if something takes less than two minutes, do it now. Small tasks pile up and cost more to remember later.",
  "When you feel overwhelmed, write everything on your mind onto paper. Then pick just one item and do it. Clarity usually follows action.",
  "To listen well, let people finish, then repeat back what you heard in your own words. Most people mainly want to feel truly understood.",
  "Store passwords in a password manager and turn on two factor login for email and banking. Most account breaches start with a reused password.",
  "To learn something faster, test yourself instead of rereading. Trying to recall information strengthens memory far more than looking at it again.",
  "Spaced repetition means reviewing material just before you would forget it, at longer and longer intervals. It is the most efficient way to memorize.",
  "When negotiating salary, let them name a number first if you can, and always ask whether there is any flexibility. The worst answer is no.",
  "If someone is choking and cannot speak or cough, call for help and give firm upward thrusts just above their navel until the object comes out.",
  "To make a decision you keep putting off, set a deadline, list your top options, and pick the one you would be least likely to regret.",
  "A good apology names what you did, acknowledges how it affected the other person, and says what you will do differently. Skip the excuses.",
  "Before buying something expensive, wait a few days. If you still want it after the excitement fades, it is more likely a good purchase.",
  "To stop procrastinating, make the first step ridiculously small. Open the document and write one sentence. Starting is the hardest part.",
  "When reading something important, write a one sentence summary afterward. If you cannot, you probably did not understand it as well as you thought.",
  "Drink a glass of water when you wake up, get some sunlight within the first hour, and your body clock will thank you all day.",
  "To give a good talk, tell people what you will say, say it, and then tell them what you said. Repetition helps listeners follow along.",
  "Batch similar tasks together. Answer all your messages at set times instead of all day, and you will protect long stretches of focus.",
  "Compound interest works for savings and against debt. Paying off a high interest credit card is often the best return you can get.",
  "When you are stuck on a problem, explain it out loud to someone, or even to a rubber duck. Saying it plainly often reveals the answer.",
  "Keep a short list of three priorities for the day. When something new comes up, ask whether it is more important than those three.",

  // Why things are the way they are
  "The sky is blue because air scatters short blue wavelengths of sunlight much more than red ones, so blue light reaches your eyes from every direction.",
  "Sunsets look red and orange because sunlight passes through more air near the horizon, scattering away the blue and leaving the warmer colors behind.",
  "Onions make you cry because cutting them releases a gas that reacts with the water in your eyes to form a mild irritant.",
  "Your fingers wrinkle in water because your nervous system tightens blood vessels under the skin, and scientists think the ridges may improve grip on wet things.",
  "We have seasons because Earth is tilted. For half the year your hemisphere leans toward the sun and gets more direct light, then it leans away.",
  "Leaves change color in autumn because trees stop making green chlorophyll, which reveals yellow and orange pigments that were hidden there all along.",
  "Ice is slippery because a thin layer of loosely bound water molecules forms on its surface, acting almost like a liquid even below freezing.",
  "Yawning seems to be contagious because of social connection. People are more likely to yawn after seeing a close friend or family member yawn.",
  "Cats purr by rapidly twitching the muscles in their voice box. They purr when content, but sometimes also when stressed or in pain.",
  "Planes leave white trails because hot, humid engine exhaust freezes into ice crystals in the cold upper air, forming thin clouds called contrails.",
  "Bread rises because yeast eats sugar and releases carbon dioxide. Gluten in the dough traps those bubbles, making the loaf light and airy.",
  "You get goosebumps because tiny muscles pull your hairs upright. For furry ancestors it trapped warmth or looked bigger to predators.",
  "Coffee keeps you awake because caffeine blocks adenosine, a chemical that builds up in your brain during the day and makes you feel sleepy.",
  "The ocean is salty because rain slowly dissolves minerals from rocks, and rivers carry them to the sea, where water evaporates but salt stays.",
  "Popcorn pops because each kernel holds a little water. When heated, the water turns to steam, pressure builds, and the hard shell bursts open.",
  "Your voice sounds strange on recordings because you normally hear it partly through the bones of your skull, which adds deeper tones.",
  "Bubbles are round because surface tension pulls the film into the shape with the smallest surface area for the air inside, which is a sphere.",
  "Spicy food feels hot because capsaicin triggers the same nerve receptors that detect heat, so your brain thinks your mouth is burning.",
  "We see lightning before hearing thunder because light travels about a million times faster than sound. Count the seconds to estimate the distance.",
  "Metal feels colder than wood at the same temperature because metal pulls heat away from your skin much faster, and your nerves sense that loss.",
  "Mirrors seem to flip left and right, but they really flip front and back. Your reflection faces you, so its right hand looks like its left.",
  "The moon always shows us the same face because its spin has slowed to match its orbit, so it turns exactly once each time it circles Earth.",
  "Apples turn brown after cutting because an enzyme reacts with oxygen in the air. Lemon juice slows it down by making the surface more acidic.",
  "Stars twinkle because their light passes through moving layers of air that bend it slightly, while planets look steadier because they appear as tiny discs.",
  "Rainbows form when sunlight enters raindrops, bends, reflects off the back, and splits into colors, so you always see one with the sun behind you.",
];
